name: lint_quido
version: 0.3.6
description: Collection of Flutter lints that we use and follow in Miquido
repository: https://github.com/miquido/lint_quido
issue_tracker: https://github.com/miquido/lint_quido/issues
homepage: https://github.com/miquido/lint_quido
documentation: https://github.com/miquido/lint_quido

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.5"

dependencies:
  dart_code_metrics: ^4.21.2
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
